#!/usr/bin/env bash
set -euo pipefail

# Fetches a pinned infra-kit release into a consumer's vendor directory and
# records version and digest in infra-kit.lock.
#
# This is the only command that reaches the network. `validate`, `plan`, and
# `apply` verify the committed bytes offline against the lock and never
# download anything — an upgrade is a reviewed commit, not a side effect.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=digest.sh
source "${SCRIPT_DIR}/digest.sh"

usage() {
  cat <<'EOF'
Usage:
  sync.sh --version VERSION --vendor-dir DIR [--repo OWNER/NAME] [--source PATH]

Downloads infra-kit VERSION, replaces DIR with its hack/ directory, and writes
DIR/../infra-kit.lock recording the version and digest.

  --source PATH   Vendor from a local checkout instead of downloading. Used by
                  the tests and when developing infra-kit itself.
EOF
}

version=""
vendor_dir=""
repo="fridthjof-labs/infra-kit"
source_path=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) version="$2"; shift 2 ;;
    --vendor-dir) vendor_dir="$2"; shift 2 ;;
    --repo) repo="$2"; shift 2 ;;
    --source) source_path="$2"; shift 2 ;;
    -h | --help) usage; exit 0 ;;
    *) echo "error: unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ -z "$version" || -z "$vendor_dir" ]]; then
  echo "error: --version and --vendor-dir are required" >&2
  usage >&2
  exit 1
fi

umask 077
staging="$(mktemp -d "${TMPDIR:-/tmp}/infra-kit-sync.XXXXXX")"
trap 'rm -rf -- "$staging"' EXIT

if [[ -n "$source_path" ]]; then
  cp -R "${source_path%/}/hack" "$staging/hack"
else
  if ! command -v curl >/dev/null 2>&1; then
    echo "error: curl is not installed" >&2
    exit 1
  fi
  tarball="${staging}/infra-kit.tar.gz"
  url="https://github.com/${repo}/archive/refs/tags/${version}.tar.gz"
  if ! curl -fsSL --proto '=https' --tlsv1.2 "$url" -o "$tarball"; then
    echo "error: could not download ${url}" >&2
    exit 1
  fi
  tar -xzf "$tarball" -C "$staging"
  extracted="$(find "$staging" -maxdepth 1 -type d -name 'infra-kit-*' | head -1)"
  if [[ -z "$extracted" || ! -d "$extracted/hack" ]]; then
    echo "error: ${version} does not contain a hack/ directory" >&2
    exit 1
  fi
  mv "$extracted/hack" "$staging/hack"
fi

digest="$(infra_kit_tree_digest "$staging/hack")"

# Replace atomically-ish: remove then move, so a partial copy cannot be left
# behind looking like a valid vendor directory.
rm -rf -- "$vendor_dir"
mkdir -p "$(dirname "$vendor_dir")"
mv "$staging/hack" "$vendor_dir"
chmod -R u+rwX,go-w "$vendor_dir"
find "$vendor_dir" -name '*.sh' -exec chmod +x {} +

lock="$(dirname "$vendor_dir")/infra-kit.lock"
cat > "$lock" <<EOF
# Generated by sync.sh. Verified offline by verify.sh — do not edit by hand,
# and do not edit the vendored files: both make the digest fail.
version = ${version}
digest = sha256:${digest}
EOF
chmod 644 "$lock"

echo "vendored infra-kit ${version} into ${vendor_dir}"
echo "digest sha256:${digest}"
echo "lock ${lock}"
